/*
35%

If we are presented with the first k terms of a sequence it is impossible to say with certainty the value of the next term, as there are infinitely many polynomial functions that can model the sequence.

As an example, let us consider the sequence of cube numbers. This is defined by the generating function,

$u_n = n^3: 1, 8, 27, 64, 125, 216, ...$

Suppose we were only given the first two terms of this sequence. Working on the principle that "simple is best" we should assume a linear relationship and predict the next term to be 15 (common difference 7). Even if we were presented with the first three terms, by the same principle of simplicity, a quadratic relationship should be assumed.

We shall define $OP(k, n)$ to be the n-th term of the optimum polynomial generating function for the first k terms of a sequence. It should be clear that $OP(k, n)$ will accurately generate the terms of the sequence for n ≤ k, and potentially the first incorrect term (FIT) will be $OP(k, k+1)$; in which case we shall call it a bad OP (BOP).

As a basis, if we were only given the first term of sequence, it would be most sensible to assume constancy; that is, for n ≥ 2, $OP(1, n) = u_1$.

Hence we obtain the following OPs for the cubic sequence:

$OP(1, n) = 1 					1, *1*, 1, 1, ...$
$OP(2, n) = 7n−6 				1, 8, *15*, ...$
$OP(3, n) = 6n^2−11n+6      	1, 8, 27, *58*, ...$
$OP(4, n) = n^3 				1, 8, 27, 64, 125, ...$

Clearly no BOPs exist for k ≥ 4.

By considering the sum of FITs generated by the BOPs (indicated in red above), we obtain 1 + 15 + 58 = 74.

Consider the following tenth degree polynomial generating function:

$u_n = 1 − n + n^2 − n^3 + n^4 − n^5 + n^6 − n^7 + n^8 − n^9 + n^10$

Find the sum of FITs for the BOPs.
*/

#include <algorithm>
#include <climits>
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <vector>

using namespace std;

long long u(int n)
{
	long long r = 0;
	long long b = 1;
	long long s = 1;

	for (int i = 0; i <= 10; ++i)
	{
		r += s * b;
		b *= n;
		s *= -1;
	}

	return r;

	//return n * n * n;
}

double lagrange(vector<pair<double, double>>& k, int x)
{
	int n = k.size();
	double y = 0;

	for (int i = 0; i < n; ++i)
	{
		vector<double> nu, de;
		auto [x1, y1] = k[i];

		for (int j = 0; j < n; ++j)
		{
			if (j == i)
				continue;

			auto [x2, y2] = k[j];

			nu.push_back(x - x2);
			de.push_back(x1 - x2);
		}

		nu.push_back(y1);

		double sim = 1;

		for (auto a : nu)
			sim *= a;

		for (auto b : de)
			sim /= b;

		y += sim;
	}

	return y;
}

void test_lagrange()
{
	vector<pair<double, double>> k = {
		{4, 10}, 
		{5, 5.25}, 
		{6, 1}
	};

	cout << lagrange(k, 18) << "\n";
}

long long euler()
{
	vector<pair<double, double>> k = {
		{1, 1}
	};

	long long ret = 0;

	for (int i = 2; ; ++i)
	{
		auto op = lagrange(k, i);
		auto un = u(i);

		if (op == un)
			break;

		ret += op;

		cout << i << " " << op << "\n";
		k.push_back({i, un});
	}

	return ret;
}

int main()
{
	//test_lagrange();
	cout << euler() << "\n";

	return 0;
}
