/*
5%

Consider all integer combinations of a<sup>b</sup> for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

	2<sup>2</sup>=4, 2<sup>3</sup>=8, 2<sup>4</sup>=16, 2<sup>5</sup>=32
	3<sup>2</sup>=9, 3<sup>3</sup>=27, 3<sup>4</sup>=81, 3<sup>5</sup>=243
	4<sup>2</sup>=16, 4<sup>3</sup>=64, 4<sup>4</sup>=256, 4<sup>5</sup>=1024
	5<sup>2</sup>=25, 5<sup>3</sup>=125, 5<sup>4</sup>=625, 5<sup>5</sup>=3125

If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

	4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by a<sup>b</sup> for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
*/

#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <iomanip>
#include <map>
#include <numeric>
#include <set>
#include <stack>
#include <string>
#include <queue>

using namespace std;

void print(vector<int> &v)
{
	for (int x : v)
		cout << x << " ";
	cout << endl;
}

void mul(vector<int> &a, vector<int> &b)
{
	vector<int> t(a.size() + b.size());
	int c = 0;

	for (int i = 0; i < a.size(); ++i)
		for (int j = 0; j < b.size(); ++j)
			t[i + j] += a[i] * b[j];

	for (int k = 0; k < a.size(); ++k)
	{
		a[k] = t[k] + c;
		c = a[k] / 10;
		a[k] %= 10;
	}

	for (int k = a.size(); k < t.size(); ++k)
	{
		a.push_back(t[k] + c);
		c = a.back() / 10;
		a.back() %= 10;
	}

	a.push_back(c);

	while (a.size() && a.back() == 0)
		a.pop_back();

	//print(a);
}

vector<int> pow(int a, int b)
{
	vector<int> base;
	vector<int> ret = {1};

	while (a)
	{
		base.push_back(a % 10);
		a /= 10;
	}
	
	while (b)
	{
		if (b & 1)
			mul(ret, base);

		mul(base, base);
		b >>= 1;
	}

	return ret;
}

int euler(int n)
{
	set<vector<int>> ss;

	for (int a = 2; a <= n; ++a)
		for (int b = 2; b <= n; ++b)
			ss.insert(pow(a, b));

	return ss.size();
}

int main()
{
	cout << euler(5) << endl;
	cout << euler(100) << endl;

	return 0;
}
