/*
5%

Pentagonal numbers are generated by the formula, P<sub>n</sub>=n(3n−1)/2. The first ten pentagonal numbers are:

	1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P<sub>4</sub> + P<sub>7</sub> = 22 + 70 = 92 = P<sub>8</sub>. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P<sub>j</sub> and P<sub>k</sub>, for which their sum and difference are pentagonal and D = |P<sub>k</sub> − P<sub>j</sub>| is minimised; what is the value of D?
*/

#include <algorithm>
#include <climits>
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <iomanip>
#include <map>
#include <numeric>
#include <set>
#include <stack>
#include <string>
#include <queue>

using namespace std;

int euler()
{
	set<long long> pen;

	for (long long i = 1; i < 10000; ++i)
		pen.insert(i * (3 * i - 1) / 2);


	for (auto j : pen)
	{
		for (auto k : pen)
		{
			if (k <= j)
				continue;

			if (pen.count(k + j) && pen.count(k - j))
			{
				cout << j << " " << k << endl;
			}
		}
	}


	return 0;
}

int main()
{
	cout << euler() << endl;

	return 0;
}
