/*
5%

<p>Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:</p>
<table><tr><td>Triangle</td>
<td> </td>
<td>$T_n=n(n+1)/2$</td>
<td> </td>
<td>$1, 3, 6, 10, 15, \dots$</td>
</tr><tr><td>Pentagonal</td>
<td> </td>
<td>$P_n=n(3n - 1)/2$</td>
<td> </td>
<td>$1, 5, 12, 22, 35, \dots$</td>
</tr><tr><td>Hexagonal</td>
<td> </td>
<td>$H_n=n(2n - 1)$</td>
<td> </td>
<td>$1, 6, 15, 28, 45, \dots$</td>
</tr></table><p>It can be verified that $T_{285} = P_{165} = H_{143} = 40755$.</p>
<p>Find the next triangle number that is also pentagonal and hexagonal.</p>
*/

#include <algorithm>
#include <climits>
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <iomanip>
#include <map>
#include <numeric>
#include <set>
#include <stack>
#include <string>
#include <queue>

using namespace std;

int euler()
{
	long long i = 3, j = 3, k = 3;
	vector<long long> tri = {1, 3};
	vector<long long> pen = {1, 5};
	vector<long long> hex = {1, 6};

	while (true)
	{
		if (tri.back() == pen.back() && pen.back() == hex.back())
		{
			cout << tri.back() << endl;

			tri.push_back(i * (i + 1) / 2);
			++ i;
			pen.push_back(j * (3 * j - 1) / 2);
			++ j;
			hex.push_back(k * (2 * k - 1));
			++ k;
		}
		else if (tri.back() <= pen.back() && tri.back() <= hex.back())
		{
			tri.push_back(i * (i + 1) / 2);
			++ i;
		}
		else if (pen.back() <= tri.back() && pen.back() <= hex.back())
		{
			pen.push_back(j * (3 * j - 1) / 2);
			++ j;
		}
		else if (hex.back() <= tri.back() && hex.back() <= pen.back())
		{
			hex.push_back(k * (2 * k - 1));
			++ k;
		}
		else
		{
			cout << "!" << endl;
			break;
		}

		//cout << i << " " << j << " " << k << endl;
	}

	return 0;
}

int main()
{
	cout << euler() << endl;

	return 0;
}
